package by.epum.training.oop.entity;

public enum IncomeType {
	 MAJOR_SALARY,
	 ADDITIONAL_SALARY,
	 ROYALTY,
	 PROPERTY_SALE,
	 ABROAD_REMITTANCE,
	 MAJOR_MATERIAL_SUPPORT,
	 ADDITIONAL_MATERIAL_SUPPORT,
	 CHILDREN_CAMP_VOUCHER;
}
