package by.epum.training.oop.command;

public enum CommandName {
	GET_BY_ID,
	FIND_BY_LAST_NAME,
	CALCULATE_ANNUAL_TAX,
	GET_INCOMES,
	DISPLAY_ANNUAL_TAX,
	SORT_ANNUAL_TAX_BY_TAX,
	GET_TAX_DATA,
	GET_MONTH_INCOMES,
	DISPLAY_PERIOD_TAX,
    QUIT;
	
}
